# https://www.netlify.com/docs/netlify-toml-reference/
[build]
  base = "./"
  publish = "./"
  command = "npm run build"
  [build.environment]
    GIT_LFS_ENABLED = "1"
[dev]
  targetPort = 8000
[[headers]]
  for="/*"
  [headers.values]
    Link = '''
      </css/styles/index.css>; rel=preload; as=style, \
      </css/js/index.js>; rel=preload; as=script, \
      </img/icons.svg>; rel=preload; as=image
    '''
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000"
    Content-Security-Policy = '''
      default-src 'self';
      base-uri 'self';
      img-src *;
      script-src 'self' https://cdn.kernvalley.us/ https://unpkg.com/@webcomponents/custom-elements@1.2.4/ https://cdn.polyfill.io/v2/;
      style-src 'self' 'unsafe-inline' https://cdn.kernvalley.us/;
      connect-src 'self' https://api.kernvalley.us/ https://cdn.kernvalley.us/ https://unpkg.com/@webcomponents/custom-elements@1.2.4/ https://cdn.polyfill.io/v2/ https://e8640586-0899-49fe-a622-4c98878f4c31.kernvalley.us;
      worker-src: 'self';
      font-src 'self' https://cdn.kernvalley.us/;
      media-src 'none';
      child-src 'self';
      object-src: 'none';
      manifest-src 'self';
      form-action 'self';
      reflected-xss block;
      block-all-mixed-content;
      upgrade-insecure-requests;
      disown-opener;'''
# @TODO ADD `report-uri` to CSP
# [[redirects]]
  # from = ""
  # to = ""
